blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/ale468/football-simulation/security/advisories/new
    about: Report exploitable vulnerabilities privately.

